---
abstract: 'The great new Mojolicious::Plugin::SQLMaker!'
author:
  - 'Tatsuya Fukata <tatsuya.fukata@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-SQLMaker
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 1.26
  SQL::Maker: 1.07
  perl: 5.006
version: 0.01
